export const ADD_TODO = 'ADD_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SET_EDITTING_ID = 'SET_EDITTING_ID'
export const CLEAR_ALL = 'CLEAR_ALL'
export const RESET_EDITTING_ID = 'RESET_EDITTING_ID'
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS'

export const KILL_MONSTER = 'KILL_MONSTER'
export const ADD_MONSTER = 'ADD_MONSTER'
export const SUMMON_MANY_MONSTERS = 'SUMMON_MANY_MONSTERS'
export const EDIT_NAME = 'EDIT_NAME'
export const CLEAR_ALL_MONSTER = 'CLEAR_ALL_MONSTER'
export const TOGGLE_MONSTER_STATUS = 'TOGGLE_MONSTER_STATUS'

export const SUCCESS_GEN_RAN_NUM = 'SUCCESS_GEN_RAN_NUM'
export const FAIL_GEN_RAN_NUM = 'FAIL_GEN_RAN_NUM'

export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'

export const FETCH_MONSTER_STORAGE = 'FETCH_MONSTER_STORAGE'
export const FETCH_MONSTER = 'FETCH_MONSTER'

export const FETCH_DUNGEON_LIST = 'FETCH_DUNGEON_LIST'

export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST'

export const CRAWL_START = 'CRAWL_START'